services:
  mongodb:
    container_name: watch-e-commerce-mongodb
    image: mongo:8.0.5
    env_file:
      - .env.production
    ports:
      - '${DATABASE_PORT}:27017'
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    volumes:
      - ./docker-volumes/mongodb:/data/db
    networks:
      - watch-network

  redis:
    container_name: watch-e-commerce-redis
    image: redis:8.0-M02-alpine
    env_file:
      - .env.production
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - ./docker-volumes/redis:/data/db
    networks:
      - watch-network

  app:
    container_name: watch-e-commerce-app
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '${PORT}:80'
    env_file:
      - .env.production
    depends_on:
      - redis
      - mongodb
    networks:
      - watch-network

networks:
  watch-network:
    driver: bridge

volumes:
  mongodb-data:
  redis-data:
