services:
  mongodb:
    container_name: watch-e-commerce-mongodb
    image: mongo:8.0.5
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    command: ['mongod', '--auth']
    volumes:
      - ./docker-volumes/mongodb:/data/db
    # networks:
    #   - watch-e-commerce-network

  redis:
    container_name: watch-e-commerce-redis
    image: redis:8.0-M02-alpine
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./docker-volumes/redis:/data/db
    # networks:
    #   - watch-e-commerce-network

  # backend:
  #   container_name: watch-e-commerce-backend
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mongodb
  #     - redis
  #   volumes:
  #     - .:/usr/src/app
  #   networks:
  #     - watch-e-commerce-network

volumes:
  redis-data:
  mongodb-data:
# networks:
#   watch-e-commerce-network:
#     driver: bridge
