services:
  mongodb:
    container_name: watch-e-commerce-mongodb-single-node
    image: mongo:8.0.5
    ports:
      - '${DATABASE_PORT}:27017'
    environment:
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    volumes:
      - ./docker-volumes/mongodb:/data/db

  redis:
    container_name: watch-e-commerce-redis
    image: redis:8.0-M02-alpine
    ports:
      - '${REDIS_PORT}:6379'
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./docker-volumes/redis:/data/db

volumes:
  mongodb-data:
  redis-data:
